/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import Veriler.GunlukVeri;
import Veriler.Veri;

import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.net.*;
import javax.swing.JFrame;

public class VeriGirisiUI extends javax.swing.JFrame implements Runnable {

    private VeriGirisi veriGirisi;

    private Veri veri;
    ServerSocket server;

    private int xMouse, yMouse;

    public VeriGirisiUI() {
        initComponents();
        try {
            server = new ServerSocket(3333);
        } catch (Exception e) {
        }
        veriGirisi = new VeriGirisi();
        veri = new GunlukVeri();

        Thread t = new Thread(this);
        t.start();

        JTextFieldDateEditor date = ((JTextFieldDateEditor) tarihSec.getDateEditor());
        date.setBackground(new Color(129, 207, 224));

        try {
            InetAddress iAddress = InetAddress.getLocalHost();
            String server_IP = iAddress.getHostAddress();
            System.out.println("Server IP address : " + server_IP);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblKapat = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        lblSurukle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTest = new javax.swing.JTextField();
        txtVefat = new javax.swing.JTextField();
        txtIyilesen = new javax.swing.JTextField();
        txtYogun = new javax.swing.JTextField();
        txtEntube = new javax.swing.JTextField();
        txtVaka = new javax.swing.JTextField();
        btnTamamla = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tarihSec = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(42, 187, 155));

        lblKapat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblKapat.setText("X");
        lblKapat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKapat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKapatMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(236, 240, 241));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Günlük Veriler");

        lblMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMin.setText("-");
        lblMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinMouseClicked(evt);
            }
        });

        lblSurukle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblSurukleMouseDragged(evt);
            }
        });
        lblSurukle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSurukleMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(lblSurukle, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMin)
                .addGap(18, 18, 18)
                .addComponent(lblKapat)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKapat)
                            .addComponent(lblMin))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblSurukle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(19, 19, 19))
        );

        jPanel2.setBackground(new java.awt.Color(4, 147, 114));

        jLabel1.setBackground(new java.awt.Color(236, 240, 241));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 240, 241));
        jLabel1.setText("Günlük Test Sayısı: ");
        jLabel1.setToolTipText("");

        jLabel2.setBackground(new java.awt.Color(236, 240, 241));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setText("Günlük Vaka Sayısı: ");
        jLabel2.setToolTipText("");

        jLabel6.setBackground(new java.awt.Color(236, 240, 241));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Günlük Vefat Sayısı: ");
        jLabel6.setToolTipText("");

        jLabel7.setBackground(new java.awt.Color(236, 240, 241));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Günlük İyileşen Sayısı: ");
        jLabel7.setToolTipText("");

        jLabel8.setBackground(new java.awt.Color(236, 240, 241));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Günlük Yoğun Bakım Sayısı: ");
        jLabel8.setToolTipText("");

        jLabel9.setBackground(new java.awt.Color(236, 240, 241));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("Günlük Entübe Sayısı: ");
        jLabel9.setToolTipText("");

        txtTest.setBackground(new java.awt.Color(46, 49, 49));
        txtTest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTest.setForeground(new java.awt.Color(255, 255, 255));
        txtTest.setName("txtTest"); // NOI18N
        txtTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTestActionPerformed(evt);
            }
        });
        txtTest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTestKeyPressed(evt);
            }
        });

        txtVefat.setBackground(new java.awt.Color(46, 49, 49));
        txtVefat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtVefat.setForeground(new java.awt.Color(255, 255, 255));
        txtVefat.setName("txtVefat"); // NOI18N
        txtVefat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVefatKeyPressed(evt);
            }
        });

        txtIyilesen.setBackground(new java.awt.Color(46, 49, 49));
        txtIyilesen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIyilesen.setForeground(new java.awt.Color(255, 255, 255));
        txtIyilesen.setName("txtIyilesen"); // NOI18N
        txtIyilesen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIyilesenActionPerformed(evt);
            }
        });
        txtIyilesen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIyilesenKeyPressed(evt);
            }
        });

        txtYogun.setBackground(new java.awt.Color(46, 49, 49));
        txtYogun.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtYogun.setForeground(new java.awt.Color(255, 255, 255));
        txtYogun.setName("txtYogunBakim"); // NOI18N
        txtYogun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtYogunKeyPressed(evt);
            }
        });

        txtEntube.setBackground(new java.awt.Color(46, 49, 49));
        txtEntube.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEntube.setForeground(new java.awt.Color(255, 255, 255));
        txtEntube.setName("txtEntube"); // NOI18N
        txtEntube.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEntubeKeyPressed(evt);
            }
        });

        txtVaka.setBackground(new java.awt.Color(46, 49, 49));
        txtVaka.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtVaka.setForeground(new java.awt.Color(255, 255, 255));
        txtVaka.setName("txtVaka"); // NOI18N
        txtVaka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVakaKeyPressed(evt);
            }
        });

        btnTamamla.setBackground(new java.awt.Color(1, 50, 67));
        btnTamamla.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTamamla.setForeground(new java.awt.Color(255, 255, 255));
        btnTamamla.setText("Tamamla");
        btnTamamla.setName("btnTamamla"); // NOI18N
        btnTamamla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTamamlaMouseClicked(evt);
            }
        });
        btnTamamla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamamlaActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(236, 240, 241));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("Tarih:");
        jLabel3.setToolTipText("");

        tarihSec.setBackground(new java.awt.Color(4, 147, 114));
        tarihSec.setForeground(new java.awt.Color(236, 240, 241));
        tarihSec.setToolTipText("");
        tarihSec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tarihSec.setPreferredSize(new java.awt.Dimension(238, 28));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTest, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVaka, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVefat, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tarihSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIyilesen, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEntube, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYogun, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTamamla, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tarihSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtVaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtVefat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtIyilesen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtYogun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(txtEntube, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTamamla, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtIyilesen.getAccessibleContext().setAccessibleName("txtIyılesen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTestActionPerformed

    private void txtIyilesenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIyilesenActionPerformed

    }//GEN-LAST:event_txtIyilesenActionPerformed

    private void lblKapatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKapatMouseClicked
        System.exit(0);

    }//GEN-LAST:event_lblKapatMouseClicked

    private void lblMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinMouseClicked

    private void btnTamamlaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTamamlaMouseClicked

    }//GEN-LAST:event_btnTamamlaMouseClicked

    private void btnTamamlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamamlaActionPerformed

        veri.setTest(Integer.parseInt(txtTest.getText()));
        veri.setVaka(Integer.parseInt(txtVaka.getText()));
        veri.setVefat(Integer.parseInt(txtVefat.getText()));
        veri.setIyilesen(Integer.parseInt(txtIyilesen.getText()));
        veri.setYogunBakim(Integer.parseInt(txtYogun.getText()));
        veri.setEntube(Integer.parseInt(txtEntube.getText()));
        veri.setTarih(tarihSec.getDate());

        veriGirisi.setVeriGirildiMi(true);


    }//GEN-LAST:event_btnTamamlaActionPerformed

    private void lblSurukleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSurukleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_lblSurukleMouseDragged

    private void lblSurukleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSurukleMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_lblSurukleMousePressed

    private void txtTestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTestKeyPressed

        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyCode() == 8) {
            txtTest.setEditable(true);

        } else {
            txtTest.setEditable(false);

        }
    }//GEN-LAST:event_txtTestKeyPressed

    private void txtVakaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVakaKeyPressed

        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyCode() == 8) {
            txtVaka.setEditable(true);

        } else {
            txtVaka.setEditable(false);

        }
    }//GEN-LAST:event_txtVakaKeyPressed

    private void txtVefatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVefatKeyPressed

        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyCode() == 8) {
            txtVefat.setEditable(true);

        } else {
            txtVefat.setEditable(false);

        }
    }//GEN-LAST:event_txtVefatKeyPressed

    private void txtIyilesenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIyilesenKeyPressed

        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyCode() == 8) {
            txtIyilesen.setEditable(true);

        } else {
            txtIyilesen.setEditable(false);

        }
    }//GEN-LAST:event_txtIyilesenKeyPressed

    private void txtYogunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYogunKeyPressed

        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyCode() == 8) {
            txtYogun.setEditable(true);

        } else {
            txtYogun.setEditable(false);

        }
    }//GEN-LAST:event_txtYogunKeyPressed

    private void txtEntubeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEntubeKeyPressed
        if ((evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') || evt.getKeyCode() == 8) {
            txtEntube.setEditable(true);

        } else {
            txtEntube.setEditable(false);

        }
    }//GEN-LAST:event_txtEntubeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeriGirisiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeriGirisiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeriGirisiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeriGirisiUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeriGirisiUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTamamla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblKapat;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblSurukle;
    private com.toedter.calendar.JDateChooser tarihSec;
    private javax.swing.JTextField txtEntube;
    private javax.swing.JTextField txtIyilesen;
    private javax.swing.JTextField txtTest;
    private javax.swing.JTextField txtVaka;
    private javax.swing.JTextField txtVefat;
    private javax.swing.JTextField txtYogun;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            try {
                var socket = server.accept();
                var client = new Client(socket, veri);
                veriGirisi.aboneEkle(client);

            } catch (Exception e) {
            }

        }

    }
}
