/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clients;

import Veriler.BosVeri;
import Veriler.GunlukVeri;
import Veriler.Veri;
import Is.ToplamVeriYonetimi;
import VeriErisim.TxtToplamVeriDal;
import Veriler.ToplamVeri;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class GrafikliVeri extends javax.swing.JFrame implements Runnable {

    private static GrafikliVeri grafikliVeri;

    private Socket clientSocket = null;
    private ObjectInputStream ois = null;

    private final int port = 3333;
    private final String host = "localhost";

    private Veri gunlukVeri;
    private Veri toplamVeri;

    private Vector<Veri> toplamVeriler;

    private ToplamVeriYonetimi toplamVeriYonetimi;

    private final GrafikCizim grafikCiz;

    private boolean veriDegistiMi, bosVeriMi = false;
    
     JPanel grafik;

    BufferedImage img = null;

    private int xMouse;
    private int yMouse;

    private GrafikliVeri() {
        initComponents();

        grafikCiz = new GrafikCizim();

        toplamVeriYonetimi = new ToplamVeriYonetimi(new TxtToplamVeriDal("GrafikToplamVeriler"));

        toplamVeri = toplamVeriYonetimi.sonVeriGetir();

        if (!(toplamVeri instanceof BosVeri)) {
            toplamVeriler = toplamVeriYonetimi.hepsiniGetir();
        } else {
            gunlukVeri = new BosVeri();
            toplamVeriler = new Vector<Veri>();
            toplamVeriler.add(toplamVeri);
            bosVeriMi = true;
        }
        
        grafik =grafikCiz.grafikOlustur(toplamVeriler);
        grafik.setBounds(0, 0, 494, 276);
       
        pnlGrafik.add(grafik);
        pnlGrafik.setComponentZOrder(grafik, 0);
        
        //grafikOlustur();
        
        labelGuncelle();

        this.setLocationRelativeTo(null);

    }

    public synchronized static GrafikliVeri nesneUret() {
        if (grafikliVeri == null) {
            grafikliVeri = new GrafikliVeri();
        }
        return grafikliVeri;
    }

    private void grafikOlustur() {
     grafik = grafikCiz.grafikOlustur(toplamVeriler); 
     grafik.setBounds(0, 0, 494, 276);
     pnlGrafik.removeAll();
     pnlGrafik.add(grafik);
     pnlGrafik.setComponentZOrder(grafik, 0);
     pnlGrafik.repaint();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel30 = new javax.swing.JLabel();
        lblSurukle3 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblEntube = new javax.swing.JLabel();
        lblVefat = new javax.swing.JLabel();
        lblYogunBakim = new javax.swing.JLabel();
        lblVaka = new javax.swing.JLabel();
        lblTest = new javax.swing.JLabel();
        lblIyilesen = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        lblKapat1 = new javax.swing.JLabel();
        lblIndir = new javax.swing.JLabel();
        pnlGrafik = new javax.swing.JPanel();
        lblSurukle4 = new javax.swing.JLabel();

        jLabel30.setBackground(new java.awt.Color(236, 240, 241));
        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(236, 240, 241));
        jLabel30.setText("TOPLAM TEST SAYISI:");
        jLabel30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSurukle3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblSurukleMouseDragged(evt);
            }
        });
        lblSurukle3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSurukleMousePressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel.setBackground(new java.awt.Color(4, 147, 114));
        panel.setPreferredSize(new java.awt.Dimension(500, 392));

        jLabel25.setBackground(new java.awt.Color(236, 240, 241));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(236, 240, 241));
        jLabel25.setText("TOPLAM TEST SAYISI:");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel26.setBackground(new java.awt.Color(236, 240, 241));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(236, 240, 241));
        jLabel26.setText("TOPLAM VAKA SAYISI:");
        jLabel26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel27.setBackground(new java.awt.Color(236, 240, 241));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(236, 240, 241));
        jLabel27.setText("TOPLAM ENTÜBE SAYISI:");
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel28.setBackground(new java.awt.Color(236, 240, 241));
        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(236, 240, 241));
        jLabel28.setText("TOPLAM VEFAT SAYISI:");
        jLabel28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel29.setBackground(new java.awt.Color(236, 240, 241));
        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(236, 240, 241));
        jLabel29.setText("TOPLAM YOĞUN BAKIM SAYISI:");
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel31.setBackground(new java.awt.Color(236, 240, 241));
        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(236, 240, 241));
        jLabel31.setText("TOPLAM İYİLEŞEN SAYISI:");
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblEntube.setBackground(new java.awt.Color(236, 240, 241));
        lblEntube.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEntube.setForeground(new java.awt.Color(236, 240, 241));
        lblEntube.setText("1.171.138");

        lblVefat.setBackground(new java.awt.Color(236, 240, 241));
        lblVefat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVefat.setForeground(new java.awt.Color(236, 240, 241));
        lblVefat.setText("1.171.138");

        lblYogunBakim.setBackground(new java.awt.Color(236, 240, 241));
        lblYogunBakim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblYogunBakim.setForeground(new java.awt.Color(236, 240, 241));
        lblYogunBakim.setText("1.171.138");

        lblVaka.setBackground(new java.awt.Color(236, 240, 241));
        lblVaka.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVaka.setForeground(new java.awt.Color(236, 240, 241));
        lblVaka.setText("1.171.138");

        lblTest.setBackground(new java.awt.Color(236, 240, 241));
        lblTest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTest.setForeground(new java.awt.Color(236, 240, 241));
        lblTest.setText("1.171.138");

        lblIyilesen.setBackground(new java.awt.Color(236, 240, 241));
        lblIyilesen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIyilesen.setForeground(new java.awt.Color(236, 240, 241));
        lblIyilesen.setText("1.171.138");

        jLabel32.setBackground(new java.awt.Color(236, 240, 241));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(236, 240, 241));
        jLabel32.setText("TÜRKİYE GÜNLÜK KORONAVİRÜS TABLOSU");

        lblKapat1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblKapat1.setText("X");
        lblKapat1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKapat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKapat1MouseClicked(evt);
            }
        });

        lblIndir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblIndir.setText("-");
        lblIndir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIndir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIndirMouseClicked(evt);
            }
        });

        pnlGrafik.setPreferredSize(new java.awt.Dimension(494, 276));

        javax.swing.GroupLayout pnlGrafikLayout = new javax.swing.GroupLayout(pnlGrafik);
        pnlGrafik.setLayout(pnlGrafikLayout);
        pnlGrafikLayout.setHorizontalGroup(
            pnlGrafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );
        pnlGrafikLayout.setVerticalGroup(
            pnlGrafikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        lblSurukle4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblSurukle4MouseDragged(evt);
            }
        });
        lblSurukle4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSurukle4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTest)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblVaka)
                                            .addComponent(lblVefat)
                                            .addComponent(lblYogunBakim)
                                            .addComponent(lblEntube)
                                            .addComponent(lblIyilesen))
                                        .addGap(83, 83, 83)
                                        .addComponent(pnlGrafik, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(lblSurukle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIndir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKapat1)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSurukle4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblKapat1)
                        .addComponent(lblIndir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(lblTest))
                        .addGap(35, 35, 35)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(lblVaka))
                        .addGap(32, 32, 32)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(lblVefat))
                        .addGap(31, 31, 31)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(lblYogunBakim))
                        .addGap(22, 22, 22)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(lblEntube))
                        .addGap(24, 24, 24)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(lblIyilesen))
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlGrafik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            clientSocket = new Socket(host, port);
            ois = new ObjectInputStream(clientSocket.getInputStream());
            System.out.println("Baglantı başarılı.");
            Thread t = new Thread(this);
            t.start();

        } catch (UnknownHostException e) {
            System.err.println(e.getMessage());
        } catch (IOException e) {
            System.err.println("Bağlantı sağlanamadı");

        }

    }//GEN-LAST:event_formWindowOpened

    private void lblKapat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKapat1MouseClicked
        Object[] options = {"Evet",
            "Hayır!"};
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showOptionDialog(null, "Kapatmak istiyor musunuz?", "Soru",
                dialogButton, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (dialogResult == JOptionPane.YES_OPTION) {

            try {
                clientSocket.close();
                ois.close();

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            System.exit(0);
        }
    }//GEN-LAST:event_lblKapat1MouseClicked

    private void lblIndirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndirMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblIndirMouseClicked

    private void lblSurukleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSurukleMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_lblSurukleMousePressed

    private void lblSurukleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSurukleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_lblSurukleMouseDragged

    private void lblSurukle4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSurukle4MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_lblSurukle4MouseDragged

    private void lblSurukle4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSurukle4MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_lblSurukle4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrafikliVeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrafikliVeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrafikliVeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrafikliVeri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                nesneUret().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel lblEntube;
    private javax.swing.JLabel lblIndir;
    private javax.swing.JLabel lblIyilesen;
    private javax.swing.JLabel lblKapat1;
    private javax.swing.JLabel lblSurukle;
    private javax.swing.JLabel lblSurukle1;
    private javax.swing.JLabel lblSurukle2;
    private javax.swing.JLabel lblSurukle3;
    private javax.swing.JLabel lblSurukle4;
    private javax.swing.JLabel lblTest;
    private javax.swing.JLabel lblVaka;
    private javax.swing.JLabel lblVefat;
    private javax.swing.JLabel lblYogunBakim;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel pnlGrafik;
    // End of variables declaration//GEN-END:variables
    @Override
    public void run() {
        while (true) {
            try {
                gunlukVeri = (GunlukVeri) ois.readObject();
                if (bosVeriMi) {
                    toplamVeri = new ToplamVeri();
                    toplamVeriYonetimi.setToplamVeri(toplamVeri);
                }
                toplamVeriYonetimi.Hesapla(gunlukVeri);
                toplamVeriEkle();
                if (toplamVeriler.get(0) instanceof BosVeri) {
                    toplamVeriler.remove(0);
                }
                grafikCiz.grafikOlustur(toplamVeriler);
                grafikOlustur();
                labelGuncelle();
                veriDegistiMi = true;
                bosVeriMi = false;
                if (veriDegistiMi && !bosVeriMi) {
                    toplamVeriYonetimi.ekle(toplamVeri);
                }

            } catch (Exception e) {
                System.err.print("veri gelmedi");

            }

        }
    }

    private void labelGuncelle() {
        lblTest.setText(String.valueOf(toplamVeri.getTest()));
        lblVaka.setText(String.valueOf(toplamVeri.getVaka()));
        lblVefat.setText(String.valueOf(toplamVeri.getVefat()));
        lblYogunBakim.setText(String.valueOf(toplamVeri.getYogunBakim()));
        lblEntube.setText(String.valueOf(toplamVeri.getEntube()));
        lblIyilesen.setText(String.valueOf(toplamVeri.getIyilesen()));
    }
    
    private void toplamVeriEkle(){
        Veri v = new ToplamVeri();
        v.setEntube(toplamVeri.getEntube());
        v.setIyilesen(toplamVeri.getIyilesen());
        v.setTarih(toplamVeri.getTarih());
        v.setTest(toplamVeri.getTest());
        v.setYogunBakim(toplamVeri.getYogunBakim());
        v.setVefat(toplamVeri.getVefat());
        v.setVaka(toplamVeri.getVaka());
        
        toplamVeriler.add(v);
    }

}
