/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clients;

import Is.GunlukVeriYonetimi;
import Is.ToplamVeriYonetimi;
import VeriErisim.TxtGunlukVeriDal;
import VeriErisim.TxtToplamVeriDal;
import Veriler.BosVeri;
import Veriler.GunlukVeri;
import Veriler.ToplamVeri;
import Veriler.Veri;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cetin
 */
public class GunlukTablo extends javax.swing.JFrame implements Runnable {

    private static GunlukTablo gunlukTablo;

    private static Socket clientSocket = null;
    private static ObjectInputStream ois = null;

    private static int port = 3333;
    private static String host = "localhost";

    private Veri gunlukVeri;
    private Veri toplamVeri;

    private GunlukVeriYonetimi gunlukVeriYonetimi;
    private ToplamVeriYonetimi toplamVeriYonetimi;

    private int xMouse, yMouse;

    private boolean veriDegistiMi, bosVeriMi = false;

    private GunlukTablo() {
        initComponents();
        
        //Grafik ve gunluk tablo aynı database i kullanabilirdi ama clientlerin ayrı bilgisayar olduğu varsayıldı..
        gunlukVeriYonetimi = new GunlukVeriYonetimi(new TxtGunlukVeriDal("TabloGunlukVeriler"));
        toplamVeriYonetimi = new ToplamVeriYonetimi(new TxtToplamVeriDal("TabloToplamVeriler"));

        toplamVeri = toplamVeriYonetimi.sonVeriGetir();

        if (!(toplamVeri instanceof BosVeri)) {
            gunlukVeri = gunlukVeriYonetimi.sonVeriGetir();

        } else {
            gunlukVeri = new BosVeri();
            bosVeriMi = true;

        }
        labelGuncelle();
        this.setLocationRelativeTo(null);

    }

    public synchronized static GunlukTablo nesneUret() {
        if (gunlukTablo == null) {
            gunlukTablo = new GunlukTablo();
        }
        return gunlukTablo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblVaka = new javax.swing.JLabel();
        lblVefat = new javax.swing.JLabel();
        lblYogunBakim = new javax.swing.JLabel();
        lblTest = new javax.swing.JLabel();
        lblIyilesen = new javax.swing.JLabel();
        lblEntube = new javax.swing.JLabel();
        lblYil = new javax.swing.JLabel();
        lblGun = new javax.swing.JLabel();
        lblAy = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        lblBugunVaka = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        lblBugunTest = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        lblBugunVefat = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        lblBugunIyilesen = new javax.swing.JLabel();
        lblKapat1 = new javax.swing.JLabel();
        lblIndir = new javax.swing.JLabel();
        lblSurukle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(4, 147, 114));

        jLabel25.setBackground(new java.awt.Color(236, 240, 241));
        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(236, 240, 241));
        jLabel25.setText("TOPLAM TEST SAYISI:");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel26.setBackground(new java.awt.Color(236, 240, 241));
        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(236, 240, 241));
        jLabel26.setText("TOPLAM VAKA SAYISI:");

        jLabel27.setBackground(new java.awt.Color(236, 240, 241));
        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(236, 240, 241));
        jLabel27.setText("TOPLAM VEFAT SAYISI:");

        jLabel28.setBackground(new java.awt.Color(236, 240, 241));
        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(236, 240, 241));
        jLabel28.setText("TOPLAM YOĞUN BAKIM SAYISI:");

        jLabel29.setBackground(new java.awt.Color(236, 240, 241));
        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(236, 240, 241));
        jLabel29.setText("TOPLAM ENTÜBE SAYISI:");

        jLabel30.setBackground(new java.awt.Color(236, 240, 241));
        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(236, 240, 241));
        jLabel30.setText("TOPLAM İYİLEŞEN SAYISI:");

        jLabel31.setBackground(new java.awt.Color(236, 240, 241));
        jLabel31.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(236, 240, 241));
        jLabel31.setText("TÜRKİYE GÜNLÜK KORONAVİRÜS TABLOSU");

        lblVaka.setBackground(new java.awt.Color(236, 240, 241));
        lblVaka.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVaka.setForeground(new java.awt.Color(236, 240, 241));
        lblVaka.setText("1.171.138");

        lblVefat.setBackground(new java.awt.Color(236, 240, 241));
        lblVefat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblVefat.setForeground(new java.awt.Color(236, 240, 241));
        lblVefat.setText("1.171.138");

        lblYogunBakim.setBackground(new java.awt.Color(236, 240, 241));
        lblYogunBakim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblYogunBakim.setForeground(new java.awt.Color(236, 240, 241));
        lblYogunBakim.setText("1.171.138");

        lblTest.setBackground(new java.awt.Color(236, 240, 241));
        lblTest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTest.setForeground(new java.awt.Color(236, 240, 241));
        lblTest.setText("1.171.138");

        lblIyilesen.setBackground(new java.awt.Color(236, 240, 241));
        lblIyilesen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIyilesen.setForeground(new java.awt.Color(236, 240, 241));
        lblIyilesen.setText("1.171.138");

        lblEntube.setBackground(new java.awt.Color(236, 240, 241));
        lblEntube.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEntube.setForeground(new java.awt.Color(236, 240, 241));
        lblEntube.setText("1.171.138");

        lblYil.setBackground(new java.awt.Color(236, 240, 241));
        lblYil.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblYil.setForeground(new java.awt.Color(236, 240, 241));
        lblYil.setText("2020");

        lblGun.setBackground(new java.awt.Color(236, 240, 241));
        lblGun.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblGun.setForeground(new java.awt.Color(236, 240, 241));
        lblGun.setText("4");

        lblAy.setBackground(new java.awt.Color(236, 240, 241));
        lblAy.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblAy.setForeground(new java.awt.Color(236, 240, 241));
        lblAy.setText("MAYIS");

        jPanel7.setBackground(new java.awt.Color(4, 147, 114));
        jPanel7.setPreferredSize(new java.awt.Dimension(240, 50));

        jLabel32.setBackground(new java.awt.Color(236, 240, 241));
        jLabel32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(236, 240, 241));
        jLabel32.setText("BUGÜNKÜ VAKA");

        lblBugunVaka.setBackground(new java.awt.Color(236, 240, 241));
        lblBugunVaka.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBugunVaka.setForeground(new java.awt.Color(236, 240, 241));
        lblBugunVaka.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBugunVaka.setText("1.171.138");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(lblBugunVaka)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(lblBugunVaka))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(42, 187, 155));
        jPanel8.setPreferredSize(new java.awt.Dimension(240, 50));

        jLabel33.setBackground(new java.awt.Color(236, 240, 241));
        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(236, 240, 241));
        jLabel33.setText("BUGÜNKÜ TEST");

        lblBugunTest.setBackground(new java.awt.Color(236, 240, 241));
        lblBugunTest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBugunTest.setForeground(new java.awt.Color(236, 240, 241));
        lblBugunTest.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBugunTest.setText("1.171.138");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addComponent(lblBugunTest)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(lblBugunTest))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(42, 187, 155));
        jPanel9.setPreferredSize(new java.awt.Dimension(240, 50));

        jLabel34.setBackground(new java.awt.Color(236, 240, 241));
        jLabel34.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(236, 240, 241));
        jLabel34.setText("BUGÜNKÜ VEFAT");

        lblBugunVefat.setBackground(new java.awt.Color(236, 240, 241));
        lblBugunVefat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBugunVefat.setForeground(new java.awt.Color(236, 240, 241));
        lblBugunVefat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBugunVefat.setText("1.171.138");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(lblBugunVefat)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(lblBugunVefat))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(4, 147, 114));
        jPanel10.setPreferredSize(new java.awt.Dimension(240, 50));

        jLabel35.setBackground(new java.awt.Color(236, 240, 241));
        jLabel35.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(236, 240, 241));
        jLabel35.setText("BUGÜNKÜ İYİLEŞEN");

        lblBugunIyilesen.setBackground(new java.awt.Color(236, 240, 241));
        lblBugunIyilesen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblBugunIyilesen.setForeground(new java.awt.Color(236, 240, 241));
        lblBugunIyilesen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBugunIyilesen.setText("1.171.138");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBugunIyilesen)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(lblBugunIyilesen))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblKapat1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblKapat1.setText("X");
        lblKapat1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKapat1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKapat1MouseClicked(evt);
            }
        });

        lblIndir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblIndir.setText("-");
        lblIndir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIndir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIndirMouseClicked(evt);
            }
        });

        lblSurukle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblSurukleMouseDragged(evt);
            }
        });
        lblSurukle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSurukleMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSurukle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIndir)
                .addGap(10, 10, 10)
                .addComponent(lblKapat1)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel26))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel27))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel28))
                            .addComponent(jLabel29))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTest)
                            .addComponent(lblVaka)
                            .addComponent(lblVefat)
                            .addComponent(lblYogunBakim)
                            .addComponent(lblEntube))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(lblGun))
                            .addComponent(lblAy)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblYil)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(48, 48, 48)
                        .addComponent(lblIyilesen))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel31)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(lblSurukle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKapat1)
                            .addComponent(lblIndir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                .addComponent(jLabel31)
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(lblGun)
                        .addGap(6, 6, 6)
                        .addComponent(lblAy)
                        .addGap(11, 11, 11)
                        .addComponent(lblYil))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(lblTest)
                                .addGap(37, 37, 37)
                                .addComponent(lblVaka)
                                .addGap(35, 35, 35)
                                .addComponent(lblVefat)
                                .addGap(27, 27, 27)
                                .addComponent(lblYogunBakim))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel25)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel26)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel27)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel28)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEntube)
                            .addComponent(jLabel29))))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(lblIyilesen))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblKapat1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKapat1MouseClicked
        Object[] options = {"Evet",
            "Hayır!"};
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showOptionDialog(null, "Kapatmak istiyor musunuz?", "Soru",
                dialogButton, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

        if (dialogResult == JOptionPane.YES_OPTION) {

            try {
                clientSocket.close();
                ois.close();

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            System.exit(0);
        }

    }//GEN-LAST:event_lblKapat1MouseClicked

    private void lblIndirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIndirMouseClicked

        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblIndirMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            clientSocket = new Socket(host, port);
            ois = new ObjectInputStream(clientSocket.getInputStream());
            System.out.println("Baglantı başarılı.");
            Thread t = new Thread(this);
            t.start();

        } catch (UnknownHostException e) {
            System.err.println(e.getMessage());
        } catch (IOException e) {
            System.err.println("Bağlantı sağlanamadı");

        }
    }//GEN-LAST:event_formWindowOpened

    private void lblSurukleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSurukleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_lblSurukleMouseDragged

    private void lblSurukleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSurukleMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_lblSurukleMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GunlukTablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GunlukTablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GunlukTablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GunlukTablo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                nesneUret().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblAy;
    private javax.swing.JLabel lblBugunIyilesen;
    private javax.swing.JLabel lblBugunTest;
    private javax.swing.JLabel lblBugunVaka;
    private javax.swing.JLabel lblBugunVefat;
    private javax.swing.JLabel lblEntube;
    private javax.swing.JLabel lblGun;
    private javax.swing.JLabel lblIndir;
    private javax.swing.JLabel lblIyilesen;
    private javax.swing.JLabel lblKapat1;
    private javax.swing.JLabel lblSurukle;
    private javax.swing.JLabel lblTest;
    private javax.swing.JLabel lblVaka;
    private javax.swing.JLabel lblVefat;
    private javax.swing.JLabel lblYil;
    private javax.swing.JLabel lblYogunBakim;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            try {
                gunlukVeri = (GunlukVeri) ois.readObject();
                if (bosVeriMi) {
                    toplamVeri = new ToplamVeri();
                    toplamVeriYonetimi.setToplamVeri(toplamVeri);
                }
                toplamVeriYonetimi.Hesapla(gunlukVeri);
                veriDegistiMi = true;
                bosVeriMi = false;
                labelGuncelle();
                if (veriDegistiMi && !bosVeriMi) {
                    gunlukVeriYonetimi.ekle(gunlukVeri);
                    toplamVeriYonetimi.ekle(toplamVeri);
                }

            } catch (Exception e) {
                System.err.print("veri gelmedi");

            }
        }
    }

    private void labelGuncelle() {
        var tarih = tarihGetir();
        lblBugunIyilesen.setText(String.valueOf(gunlukVeri.getIyilesen()));
        lblBugunTest.setText(String.valueOf(gunlukVeri.getTest()));
        lblBugunVaka.setText(String.valueOf(gunlukVeri.getVaka()));
        lblBugunVefat.setText(String.valueOf(gunlukVeri.getVefat()));
        lblGun.setText(tarih[0]);
        lblAy.setText(tarih[1]);
        lblYil.setText(tarih[2]);
        lblTest.setText(String.valueOf(toplamVeri.getTest()));
        lblVaka.setText(String.valueOf(toplamVeri.getVaka()));
        lblVefat.setText(String.valueOf(toplamVeri.getVefat()));
        lblYogunBakim.setText(String.valueOf(toplamVeri.getYogunBakim()));
        lblEntube.setText(String.valueOf(toplamVeri.getEntube()));
        lblIyilesen.setText(String.valueOf(toplamVeri.getIyilesen()));

    }

    private String[] tarihGetir() {
        SimpleDateFormat formatter = new SimpleDateFormat("d-MMMM-yyyy");
        var tarih = formatter.format(gunlukVeri.getTarih());
        return tarih.split("-");

    }
}
